services:
  app:
    build: .
    volumes:
      - ./packages:/app/packages
    depends_on:
      chromadb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - VECTOR_URL=http://chromadb:8000

  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8001:8000" # coz im running my slurm LLM on 8000 local port
    volumes:
      - chroma_data:/chroma/chroma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  chroma_data:
