"""LLM Service — provider-agnostic wrapper around LiteLLM.

This service abstracts away the underlying LLM provider (OpenAI, Anthropic,
or a local Slurm cluster running vLLM). It provides built-in exponential
backoff for rate limits and tracks token usage.
"""

from typing import Any

import litellm
from pydantic import BaseModel, Field
from tenacity import (
    retry,
    retry_if_exception_type,
    stop_after_attempt,
    wait_exponential,
)

from shared.config import LLMConfig
from shared.models.events import ProgressCallback, ProgressEvent, ProgressEventType


class LLMResponse(BaseModel):
    """The structured output from an LLM call."""

    content: str = Field(description="The text generated by the LLM.")
    input_tokens: int = Field(default=0, description="Tokens used by the prompt.")
    output_tokens: int = Field(default=0, description="Tokens generated.")
    model_name: str = Field(description="The exact model that served the request.")


class LLMService:
    """Wrapper around LiteLLM for robust api calls.

    Why LiteLLM? It gives us a unified API. If we switch from OpenAI
    to a local Llama 3 model on Slurm, this code doesn't change. We just
    change the config URL.
    """

    def __init__(self, config: LLMConfig):
        self.config = config

        # Configure litellm globally if we are using an OpenAI-compatible
        # custom endpoint such as Slurm vLLM
        if config.provider == "openai_compatible" and config.base_url:
            # We don't override litellm.api_base globally to prevent side effects
            # Instead we pass it per-call in `complete()`
            pass

    # Retry on specific litellm exceptions (like RateLimitError or APIConnectionError)
    @retry(
        retry=retry_if_exception_type(
            (litellm.RateLimitError, litellm.APIConnectionError)
        ),
        wait=wait_exponential(multiplier=1, min=2, max=20),
        stop=stop_after_attempt(5),
        reraise=True,
    )
    async def _execute_call(self, messages: list[dict[str, Any]], **kwargs) -> Any:
        """Execute the actual API call with built-in retries."""

        # Litellm needs to know how to route the request.
        # For generic OpenAI-compatible endpoints, we prefix with "openai/"
        model_str = self.config.model
        if self.config.provider == "openai_compatible" and not model_str.startswith(
            "openai/"
        ):
            model_str = f"openai/{model_str}"

        # Merge config defaults with overrides in kwargs
        call_kwargs = {
            "model": model_str,
            "temperature": self.config.temperature,
            "max_tokens": self.config.max_tokens,
            "messages": messages,
            **kwargs,
        }

        # If we have a custom base URL (like Slurm vLLM), pass it explicitly
        if self.config.base_url:
            call_kwargs["api_base"] = self.config.base_url

        # Passing custom keys based on provider
        if self.config.api_key:
            call_kwargs["api_key"] = self.config.api_key.get_secret_value()

        return await litellm.acompletion(**call_kwargs)

    async def complete(
        self,
        messages: list[dict[str, Any]],
        callback: ProgressCallback | None = None,
        **kwargs,
    ) -> LLMResponse:
        """Call the LLM to generate a completion.

        Args:
            messages: List of chat messages
                (OpenAI format: {"role": "...", "content": "..."}).
            callback: Optional ProgressCallback for event emitting.
            **kwargs: Extra parameters to pass to LiteLLM overrides (e.g. temperature).

        Returns:
            An LLMResponse object containing text and token metrics.
        """
        if callback:
            await callback(
                ProgressEvent(
                    event_type=ProgressEventType.GENERATING,
                    message=f"Generating response using {self.config.model}",
                )
            )

        response = await self._execute_call(messages, **kwargs)

        # Parse Litellm response object
        content = response.choices[0].message.content or ""

        # Safe extraction of token usage
        usage = response.get("usage", {})
        prompt_tokens = usage.get("prompt_tokens", 0) if usage else 0
        completion_tokens = usage.get("completion_tokens", 0) if usage else 0

        # Create our clean internal response
        return LLMResponse(
            content=content,
            input_tokens=prompt_tokens,
            output_tokens=completion_tokens,
            model_name=response.get("model", self.config.model),
        )
